---
- hosts: cpbm
  vars:
    http_port: 80
  remote_user: root
  
  tasks:
    - name: install libselinux-python
      yum: name=libselinux-python state=present

    - name: install rsync
      yum: name=rsync state=present

    - name: ensure cloud-portal is stopped
      service: name=cloud-portal state=stopped

    - name: copy birt to /usr/share/vts3/pickup/
      copy: src=./birt.war dest=/usr/share/vts3/pickup

    - name: copy custom common the jars to /usr/share/vts3/custom_impls
      copy: src=./citrix.cpbm.custom.common-2.3.1.jar  dest=/usr/share/vts3/custom_impls/

    - name: copy custom model the jars to /usr/share/vts3/custom_impls
      copy: src=./citrix.cpbm.custom.model-2.3.1.jar dest=/usr/share/vts3/custom_impls/

    - name: copy custom portal the jars to /usr/share/vts3/custom_impls
      copy: src=./citrix.cpbm.custom.portal-2.3.1.jar dest=/usr/share/vts3/custom_impls/

    - name: copy conf file locally
      fetch: src='/usr/share/vts3/config/org.eclipse.virgo.repository.properties' dest='./' flat=yes

    - name: copy local conf file to remote
      synchronize: src="./org.eclipse.virgo.repository.properties" dest="/usr/share/vts3/config/org.eclipse.virgo.repository.properties.bak"

    - name: modify conf file comment the default
      replace: dest=/usr/share/vts3/config/org.eclipse.virgo.repository.properties regexp='^default_impls' replace='#default_impls'

    - name: modify conf file uncomment the custom
      replace: dest=/usr/share/vts3/config/org.eclipse.virgo.repository.properties regexp='^#custom_impls' replace='custom_impls'

    - name: modify conf file enable custom
      replace: dest=/usr/share/vts3/config/org.eclipse.virgo.repository.properties regexp='^chain=ext,usr' replace='chain=ext,custom_impls,usr'

    - name: ensure cloud-portal is started
      service: name=cloud-portal state=started


    

