---
- hosts: cpbm
  vars:
    http_port: 80
  remote_user: root
  
  tasks:
    - name: get the current time for a timestamp
      local_action: shell date +%Y%m%d-%H%M%S
      register: time

    - name: echo the timestamp
      shell: echo "{( time.stdout }}"

    - name: install libselinux-python
      yum: name=libselinux-python state=present

    - name: install rsync
      yum: name=rsync state=present

    - name: ensure cloud-portal is stopped
      service: name=cloud-portal state=stopped

    - name: copy custom common the jars to /usr/share/vts3/custom_impls
      copy: src=./citrix.cpbm.custom.common-2.3.1.jar  dest=/usr/share/vts3/custom_impls/

    - name: copy custom model the jars to /usr/share/vts3/custom_impls
      copy: src=./citrix.cpbm.custom.model-2.3.1.jar dest=/usr/share/vts3/custom_impls/

    - name: copy custom portal the jars to /usr/share/vts3/custom_impls
      copy: src=./citrix.cpbm.custom.portal-2.3.1.jar dest=/usr/share/vts3/custom_impls/

    - name: copy conf file locally
      fetch: src='/usr/share/vts3/config/org.eclipse.virgo.repository.properties' dest='./' flat=yes

    - name: copy properties file locally
      fetch: src='/usr/share/vts3/repository/prop/cloud.properties' dest='./' flat=yes

    - name: modify cloud.properties subs locale.default
      replace: dest=/usr/share/vts3/repository/prop/cloud.properties regexp='^locale.default=en_US' replace='locale.default=ka'

    - name: modify cloud.properties add locale
      replace: dest=/usr/share/vts3/repository/prop/cloud.properties regexp='^locale.supported=en_US' replace='locale.supported=ka,en_US'

    - name: modify conf file comment the default
      replace: dest=/usr/share/vts3/config/org.eclipse.virgo.repository.properties regexp='^default_impls' replace='#default_impls'

    - name: modify conf file uncomment the custom
      replace: dest=/usr/share/vts3/config/org.eclipse.virgo.repository.properties regexp='^#custom_impls' replace='custom_impls'

    - name: modify conf file enable custom
      replace: dest=/usr/share/vts3/config/org.eclipse.virgo.repository.properties regexp='^chain=ext,usr' replace='chain=ext,custom_impls,usr'

